//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cardinfo
    {
        public int cardno { get; set; }
        public System.DateTime expdate { get; set; }
        public int cvvno { get; set; }
        public double balance { get; set; }
    }
}
