//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webprojects
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterShopping
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string membership { get; set; }
        public string shoppingpreference { get; set; }
        public string COD { get; set; }
        public string passw { get; set; }
    }
}
